export const sampleProjects = [
  {
    id: 101,
    name: "Vinhomes Grand Park",
    status: "Đang mở bán",
    type: "Căn Hộ",
    developer: "Vinhomes",
    location: "TP. Thủ Đức, TP.HCM",
    priceFrom: 2900000000,
    handover: "2026",
    minArea: 45,
    maxArea: 120,
    images: ["/duan/anh1.jpg", "/duan/anh2.jpg", "/duan/anh3.jpg"],
    details: {
      overview:
        "Khu đô thị quy mô lớn với hệ tiện ích nội khu hoàn chỉnh: công viên, trường học, TTTM và kết nối giao thông thuận tiện.",
      highlights: [
        "Đại đô thị 271ha",
        "Công viên ven sông",
        "Tiện ích all-in-one",
        "Kết nối metro",
      ],
      productTypes: ["Căn hộ", "Shophouse", "Biệt thự"],
      amenities: [
        "Công viên",
        "Trường học",
        "TTTM",
        "Bệnh viện",
        "Hồ bơi",
        "Gym",
      ],
      legal: ["Sở hữu lâu dài", "Hỗ trợ vay ngân hàng"],
      progress: ["Mở bán phân khu mới", "Nhận booking giữ chỗ"],
      notes: "Hỗ trợ vay, chính sách ưu đãi theo từng đợt mở bán.",
    },
  },

  {
    id: 102,
    name: "Masteri Thảo Điền",
    status: "Đang bán",
    type: "Biệt Thự",
    developer: "Masterise Homes",
    location: "Thảo Điền, Quận 2, TP.HCM",
    priceFrom: 5200000000,
    handover: "Đã bàn giao",
    minArea: 50,
    maxArea: 110,
    images: ["/duan/td1.jpg", "/duan/td2.jpg"],
    details: {
      overview:
        "Tọa lạc Thảo Điền, tiện ích chuẩn resort, kết nối trung tâm nhanh.",
      highlights: ["Gần Metro", "View sông", "Tiện ích cao cấp"],
      productTypes: ["1PN", "2PN", "3PN"],
      amenities: ["Hồ bơi", "Gym", "Khu BBQ", "Công viên"],
      legal: ["Sổ hồng"],
      progress: ["Đang giao dịch thứ cấp"],
      notes: "Phù hợp ở & đầu tư cho thuê.",
    },
  },
  {
    id: 103,
    name: "Masteri Thảo Điền",
    status: "Đã bàn giao",
    type: "Đất Nền",
    developer: "Masterise Homes",
    location: "TP. Thủ Đức, TP.HCM",
    priceFrom: 4200000000,
    handover: "2019",
    minArea: 48,
    maxArea: 135,
    images: ["/duan/mtd1.jpg", "/duan/mtd2.jpg", "/duan/mtd3.jpg"],
    details: {
      overview:
        "Căn hộ cao cấp ngay trung tâm Thảo Điền, kết nối trực tiếp ga Metro số 1.",
      highlights: ["Kết nối Metro", "View sông", "Thiết kế hiện đại"],
      productTypes: ["Căn hộ", "Penthouse"],
      amenities: ["Hồ bơi", "Gym", "TTTM", "Công viên nội khu"],
      legal: ["Sổ hồng lâu dài"],
      progress: ["Đã bàn giao"],
      notes: "Thanh khoản tốt, cộng đồng cư dân quốc tế.",
    },
  },
  {
    id: 104,
    name: "The Global City",
    status: "Đang mở bán",
    type: "ShopHouse",
    developer: "Masterise Homes",
    location: "TP. Thủ Đức, TP.HCM",
    priceFrom: 9800000000,
    handover: "2026",
    minArea: 60,
    maxArea: 250,
    images: ["/duan/tgc1.jpg", "/duan/tgc2.jpg", "/duan/tgc3.jpg"],
    details: {
      overview:
        "Khu đô thị chuẩn quốc tế với quy hoạch bài bản và tiện ích thương mại – giải trí.",
      highlights: ["Quy hoạch chuẩn quốc tế", "Trung tâm mới TP.HCM"],
      productTypes: ["Nhà phố", "Biệt thự", "Shophouse"],
      amenities: ["Công viên", "TTTM", "Trường học", "Khu thể thao"],
      legal: ["Sở hữu lâu dài"],
      progress: ["Đang mở bán"],
      notes: "Phù hợp đầu tư trung – dài hạn.",
    },
  },
  {
    id: 105,
    name: "Aqua City",
    status: "Đang mở bán",
    type: "Biệt Thự",
    developer: "Novaland",
    location: "Biên Hòa, Đồng Nai",
    priceFrom: 5200000000,
    handover: "2025",
    minArea: 80,
    maxArea: 300,
    images: ["/duan/ac1.jpg", "/duan/ac2.jpg", "/duan/ac3.jpg"],
    details: {
      overview:
        "Đô thị sinh thái ven sông, không gian sống xanh quy mô lớn phía Đông TP.HCM.",
      highlights: ["Ven sông", "Không gian xanh", "Quy mô lớn"],
      productTypes: ["Nhà phố", "Biệt thự"],
      amenities: ["Công viên", "Bến du thuyền", "Hồ bơi", "Trường học"],
      legal: ["Sổ riêng từng căn"],
      progress: ["Mở bán phân khu mới"],
      notes: "Thích hợp nghỉ dưỡng và an cư.",
    },
  },
  {
    id: 106,
    name: "Sunshine City Sài Gòn",
    status: "Đang mở bán",
    type: "Căn Hộ",
    developer: "Sunshine Group",
    location: "Quận 7, TP.HCM",
    priceFrom: 3900000000,
    handover: "2025",
    minArea: 55,
    maxArea: 140,
    images: ["/duan/scsg1.jpg", "/duan/scsg2.jpg"],
    details: {
      overview: "Căn hộ thông minh với thiết kế xanh, công nghệ hiện đại.",
      highlights: ["Smart home", "View sông", "Thiết kế xanh"],
      productTypes: ["Căn hộ", "Penthouse"],
      amenities: ["Hồ bơi", "Gym", "Công viên", "Sky lounge"],
      legal: ["Sở hữu lâu dài"],
      progress: ["Đang nhận booking"],
      notes: "Ưu đãi thanh toán sớm.",
    },
  },
  {
    id: 107,
    name: "Vinhomes Ocean Park",
    status: "Đã bàn giao",
    type: "Đất Nền",
    developer: "Vinhomes",
    location: "Gia Lâm, Hà Nội",
    priceFrom: 2500000000,
    handover: "2022",
    minArea: 45,
    maxArea: 130,
    images: ["/duan/vop1.jpg", "/duan/vop2.jpg"],
    details: {
      overview:
        "Đại đô thị biển hồ nhân tạo với không gian sống xanh và tiện ích đồng bộ.",
      highlights: ["Biển hồ nhân tạo", "Công viên lớn", "Quy hoạch đồng bộ"],
      productTypes: ["Căn hộ", "Shophouse", "Biệt thự"],
      amenities: ["Biển hồ", "Công viên", "Trường học", "TTTM"],
      legal: ["Sở hữu lâu dài"],
      progress: ["Đã bàn giao"],
      notes: "Thanh khoản tốt tại khu Đông Hà Nội.",
    },
  },
  {
    id: 108,
    name: "Vinhomes Smart City",
    status: "Đang mở bán",
    type: "Căn Hộ",
    developer: "Vinhomes",
    location: "Nam Từ Liêm, Hà Nội",
    priceFrom: 2300000000,
    handover: "2025",
    minArea: 43,
    maxArea: 120,
    images: ["/duan/vsc1.jpg", "/duan/vsc2.jpg"],
    details: {
      overview:
        "Khu đô thị thông minh với hệ sinh thái công nghệ và không gian sống hiện đại.",
      highlights: ["Smart city", "Công viên thể thao", "An ninh 4 lớp"],
      productTypes: ["Căn hộ", "Studio"],
      amenities: ["Công viên", "Gym", "Hồ bơi", "TTTM"],
      legal: ["Sổ hồng lâu dài"],
      progress: ["Mở bán phân khu mới"],
      notes: "Phù hợp khách trẻ và đầu tư cho thuê.",
    },
  },
  {
    id: 109,
    name: "Mizuki Park",
    status: "Đã bàn giao",
    type: "Căn Hộ",
    developer: "Nam Long",
    location: "Bình Chánh, TP.HCM",
    priceFrom: 2100000000,
    handover: "2021",
    minArea: 56,
    maxArea: 98,
    images: ["/duan/mp1.jpg", "/duan/mp2.jpg"],
    details: {
      overview:
        "Khu căn hộ ven kênh với không gian sống xanh và mật độ xây dựng thấp.",
      highlights: ["Ven kênh", "Không gian xanh", "Mật độ thấp"],
      productTypes: ["Căn hộ"],
      amenities: ["Công viên", "Hồ bơi", "Gym", "Khu BBQ"],
      legal: ["Sổ hồng riêng"],
      progress: ["Đã bàn giao"],
      notes: "Giá tốt cho người mua ở thực.",
    },
  },
  {
    id: 110,
    name: "Akari City",
    status: "Đang mở bán",
    type: "Căn Hộ",
    developer: "Nam Long",
    location: "Quận Bình Tân, TP.HCM",
    priceFrom: 1950000000,
    handover: "2026",
    minArea: 50,
    maxArea: 110,
    images: ["/duan/akari1.jpg", "/duan/akari2.jpg"],
    details: {
      overview:
        "Khu căn hộ phong cách Nhật Bản với thiết kế tối ưu và tiện ích nội khu đầy đủ.",
      highlights: ["Phong cách Nhật", "Giá hợp lý", "Tiện ích nội khu"],
      productTypes: ["Căn hộ"],
      amenities: ["Công viên", "Hồ bơi", "Khu thể thao"],
      legal: ["Sổ hồng lâu dài"],
      progress: ["Đang nhận booking"],
      notes: "Phù hợp gia đình trẻ.",
    },
  },
  {
    id: 111,
    name: "Sun Grand City Hillside",
    status: "Đang mở bán",
    type: "Hotel-Resort",
    developer: "Sun Group",
    location: "Phú Quốc, Kiên Giang",
    priceFrom: 6800000000,
    handover: "2025",
    minArea: 60,
    maxArea: 200,
    images: ["/duan/sgc1.jpg", "/duan/sgc2.jpg"],
    details: {
      overview:
        "Khu căn hộ nghỉ dưỡng trên sườn đồi với tầm nhìn biển độc đáo.",
      highlights: ["View biển", "Du lịch – nghỉ dưỡng", "Vị trí trung tâm"],
      productTypes: ["Căn hộ", "Shophouse"],
      amenities: ["Hồ bơi", "Quảng trường", "TTTM"],
      legal: ["Sở hữu có thời hạn"],
      progress: ["Đang mở bán"],
      notes: "Phù hợp đầu tư khai thác du lịch.",
    },
  },
  {
    id: 112,
    name: "The Beverly Solari",
    status: "Đang mở bán",
    type: "Căn Hộ",
    developer: "Vinhomes",
    location: "TP. Thủ Đức, TP.HCM",
    priceFrom: 5800000000,
    handover: "2026",
    minArea: 50,
    maxArea: 135,
    images: ["/duan/tbs1.jpg", "/duan/tbs2.jpg"],
    details: {
      overview:
        "Phân khu cao cấp nhất tại Vinhomes Grand Park với tiêu chuẩn sống resort.",
      highlights: ["Phân khu cao cấp", "Tiện ích riêng", "Cộng đồng tinh hoa"],
      productTypes: ["Căn hộ"],
      amenities: ["Hồ bơi resort", "Gym", "Sky garden"],
      legal: ["Sở hữu lâu dài"],
      progress: ["Đang mở bán"],
      notes: "Sản phẩm cao cấp khan hiếm.",
    },
  },
  {
    id: 113,
    name: "Charm City",
    status: "Đã bàn giao",
    type: "Căn Hộ",
    developer: "Charm Group",
    location: "Dĩ An, Bình Dương",
    priceFrom: 1800000000,
    handover: "2023",
    minArea: 45,
    maxArea: 95,
    images: ["/duan/cc1.jpg"],
    details: {
      overview:
        "Căn hộ giá tốt tại trung tâm Dĩ An, kết nối TP.HCM thuận tiện.",
      highlights: ["Giá tốt", "Vị trí trung tâm"],
      productTypes: ["Căn hộ"],
      amenities: ["Hồ bơi", "TTTM", "Gym"],
      legal: ["Sổ hồng riêng"],
      progress: ["Đã bàn giao"],
      notes: "Phù hợp đầu tư cho thuê.",
    },
  },
  {
    id: 114,
    name: "Happy One Central",
    status: "Đang mở bán",
    type: "Đất Nền",
    developer: "Vạn Xuân Group",
    location: "Thủ Dầu Một, Bình Dương",
    priceFrom: 1900000000,
    handover: "2025",
    minArea: 49,
    maxArea: 100,
    images: ["/duan/hoc1.jpg"],
    details: {
      overview: "Căn hộ trung tâm thành phố Thủ Dầu Một với thiết kế hiện đại.",
      highlights: ["Trung tâm TP", "Thiết kế hiện đại"],
      productTypes: ["Căn hộ"],
      amenities: ["Hồ bơi", "Công viên", "Gym"],
      legal: ["Sở hữu lâu dài"],
      progress: ["Đang mở bán"],
      notes: "Thanh toán linh hoạt.",
    },
  },
  {
    id: 115,
    name: "NovaWorld Phan Thiết",
    status: "Đang mở bán",
    type: "Hotel-Resort",
    developer: "Novaland",
    location: "Phan Thiết, Bình Thuận",
    priceFrom: 6200000000,
    handover: "2026",
    minArea: 80,
    maxArea: 350,
    images: ["/duan/nwpt1.jpg"],
    details: {
      overview: "Siêu đô thị du lịch – nghỉ dưỡng – giải trí quy mô lớn.",
      highlights: ["Du lịch biển", "Quy mô lớn"],
      productTypes: ["Biệt thự", "Nhà phố", "Shophouse"],
      amenities: ["Sân golf", "Bãi biển", "TTTM"],
      legal: ["Sở hữu có thời hạn"],
      progress: ["Mở bán phân khu mới"],
      notes: "Tiềm năng tăng giá dài hạn.",
    },
  },
  {
    id: 116,
    name: "FLC Premier Parc",
    status: "Đang mở bán",
    type: "Biệt Thự",
    developer: "FLC Group",
    location: "Hà Đông, Hà Nội",
    priceFrom: 7200000000,
    handover: "2025",
    minArea: 75,
    maxArea: 200,
    images: ["/duan/flc1.jpg"],
    details: {
      overview: "Khu đô thị sinh thái thấp tầng tại cửa ngõ phía Tây Hà Nội.",
      highlights: ["Thấp tầng", "Sinh thái"],
      productTypes: ["Biệt thự", "Nhà liền kề"],
      amenities: ["Công viên", "Trường học"],
      legal: ["Sổ đỏ lâu dài"],
      progress: ["Đang mở bán"],
      notes: "Số lượng giới hạn.",
    },
  },
  {
    id: 117,
    name: "The Manor Central Park",
    status: "Đang mở bán",
    type: "ShopHouse",
    developer: "Bitexco",
    location: "Hoàng Mai, Hà Nội",
    priceFrom: 8500000000,
    handover: "2024",
    minArea: 90,
    maxArea: 250,
    images: ["/duan/tmcp1.jpg"],
    details: {
      overview: "Khu đô thị cao cấp phong cách châu Âu tại trung tâm Hà Nội.",
      highlights: ["Phong cách châu Âu", "Vị trí trung tâm"],
      productTypes: ["Biệt thự", "Shophouse"],
      amenities: ["Công viên", "Hồ điều hòa"],
      legal: ["Sổ đỏ lâu dài"],
      progress: ["Đang bàn giao"],
      notes: "Phù hợp khách hàng cao cấp.",
    },
  },
  {
    id: 118,
    name: "Opal Skyline",
    status: "Sắp mở bán",
    type: "Căn Hộ",
    developer: "Đất Xanh Group",
    location: "TP. Thuận An, Bình Dương",
    priceFrom: 1700000000,
    handover: "2026",
    minArea: 45,
    maxArea: 105,
    images: ["/duan/os1.jpg"],
    details: {
      overview:
        "Căn hộ cao tầng với tầm nhìn panorama, giá hợp lý khu vực Bình Dương.",
      highlights: ["View rộng", "Giá cạnh tranh"],
      productTypes: ["Căn hộ"],
      amenities: ["Hồ bơi", "Gym", "Công viên"],
      legal: ["Sổ hồng riêng"],
      progress: ["Sắp mở bán"],
      notes: "Dễ tiếp cận cho người mua lần đầu.",
    },
  },
];
// export const sampleProducts = [
//   {
//     id: 1,
//     name: "Nhà phố Quận 7 – Khu Him Lam",
//     type: "Nhà Phố",
//     price: 8200000000,
//     area: 120,
//     address: "Nguyễn Thị Thập, Quận 7, TP.HCM",
//     bedrooms: 4,
//     bathrooms: 3,
//     direction: "Đông Nam",
//     images: ["/house1.jpg", "/house2.jpg", "/house3.jpg"],
//     details: {
//       overview:
//         "Nhà phố 1 trệt 2 lầu, khu dân cư cao cấp, an ninh 24/7, thích hợp ở lâu dài.",
//       highlights: [
//         "Gần Lotte Mart, Crescent Mall",
//         "Đường rộng, xe hơi đậu trước nhà",
//         "Sổ hồng riêng, pháp lý rõ ràng",
//       ],
//       layout: [
//         "Tầng trệt: PK + bếp + WC",
//         "Lầu 1: 2PN + WC",
//         "Lầu 2: 2PN + WC + sân phơi",
//       ],
//       amenities: ["Công viên", "Trường học", "Siêu thị"],
//       notes: "Giá còn thương lượng nhẹ.",
//     },
//   },

//   {
//     id: 2,
//     name: "Biệt thự Thảo Điền – Sân vườn rộng",
//     type: "Biệt Thự",
//     price: 24500000000,
//     area: 300,
//     address: "Xuân Thủy, Thảo Điền, TP Thủ Đức",
//     bedrooms: 5,
//     bathrooms: 6,
//     direction: "Tây Bắc",
//     images: ["/house2.jpg", "/house3.jpg", "/house1.jpg"],
//     details: {
//       overview:
//         "Biệt thự cao cấp, khu người nước ngoài sinh sống, không gian yên tĩnh.",
//       highlights: [
//         "Sân vườn lớn ~80m²",
//         "Thiết kế mở, nhiều ánh sáng",
//         "Thích hợp ở hoặc cho thuê expat",
//       ],
//       layout: [
//         "Tầng trệt: sân vườn + PK + bếp",
//         "Lầu 1: 3PN",
//         "Lầu 2: 2PN + sân thượng",
//       ],
//       amenities: ["Vincom Thảo Điền", "Metro", "Trường quốc tế"],
//       notes: "Hỗ trợ ngân hàng.",
//     },
//   },

//   {
//     id: 3,
//     name: "Căn hộ Masteri Centre Point",
//     type: "Căn Hộ",
//     price: 5200000000,
//     area: 75,
//     address: "Vinhomes Grand Park, TP Thủ Đức",
//     bedrooms: 2,
//     bathrooms: 2,
//     direction: "Đông",
//     images: ["/house3.jpg", "/house1.jpg"],
//     details: {
//       overview:
//         "Căn hộ cao cấp, full nội thất, view công viên, tiện ích chuẩn resort.",
//       highlights: ["Full nội thất", "View công viên 36ha", "An ninh 3 lớp"],
//       layout: ["2PN + 2WC", "Ban công rộng"],
//       amenities: ["Hồ bơi", "Gym", "Công viên"],
//       notes: "Nhận nhà ngay.",
//     },
//   },

//   {
//     id: 4,
//     name: "Nhà phố Phú Nhuận – Hẻm xe hơi",
//     type: "Nhà Phố",
//     price: 9600000000,
//     area: 95,
//     address: "Phan Đăng Lưu, Phú Nhuận, TP.HCM",
//     bedrooms: 3,
//     bathrooms: 3,
//     direction: "Nam",
//     images: ["/house1.jpg", "/house2.jpg"],
//     details: {
//       overview:
//         "Nhà trung tâm Phú Nhuận, hẻm xe hơi, di chuyển sân bay 5 phút.",
//       highlights: [
//         "Vị trí trung tâm",
//         "Nhà mới, vào ở ngay",
//         "Khu dân trí cao",
//       ],
//       layout: ["1 trệt 2 lầu", "3PN + 3WC"],
//       amenities: ["Sân bay", "Chợ", "Trường học"],
//       notes: "Sổ riêng, công chứng nhanh.",
//     },
//   },

//   {
//     id: 5,
//     name: "Căn hộ Vinhomes Central Park",
//     type: "Căn Hộ",
//     price: 7800000000,
//     area: 90,
//     address: "Bình Thạnh, TP.HCM",
//     bedrooms: 3,
//     bathrooms: 2,
//     direction: "Đông Bắc",
//     images: ["/house2.jpg", "/house3.jpg"],
//     details: {
//       overview: "Căn hộ cao cấp ven sông Sài Gòn, không gian sống xanh.",
//       highlights: ["View sông", "Nội khu đẳng cấp", "Cộng đồng văn minh"],
//       layout: ["3PN + 2WC"],
//       amenities: ["Công viên ven sông", "Mall", "Gym"],
//       notes: "Giá tốt trong khu.",
//     },
//   },

//   {
//     id: 6,
//     name: "Nhà phố Gò Vấp – Gần Emart",
//     type: "Nhà Phố",
//     price: 6900000000,
//     area: 85,
//     address: "Phan Văn Trị, Gò Vấp, TP.HCM",
//     bedrooms: 3,
//     bathrooms: 3,
//     direction: "Tây",
//     images: ["/house3.jpg", "/house1.jpg"],
//     details: {
//       overview: "Nhà phố khu Gò Vấp, tiện ích đầy đủ, phù hợp gia đình trẻ.",
//       highlights: ["Gần Emart", "Hẻm rộng", "Nhà mới"],
//       layout: ["1 trệt 2 lầu"],
//       amenities: ["Siêu thị", "Trường học"],
//       notes: "Có thể dọn vào ngay.",
//     },
//   },

//   {
//     id: 7,
//     name: "Biệt thự mini Quận 12",
//     type: "Biệt Thự",
//     price: 11500000000,
//     area: 180,
//     address: "Hà Huy Giáp, Quận 12, TP.HCM",
//     bedrooms: 4,
//     bathrooms: 4,
//     direction: "Bắc",
//     images: ["/house1.jpg", "/house3.jpg"],
//     details: {
//       overview:
//         "Biệt thự mini, không gian rộng rãi, thích hợp gia đình đông người.",
//       highlights: ["Sân đậu xe", "Khu yên tĩnh", "Giá tốt"],
//       layout: ["1 trệt 2 lầu"],
//       amenities: ["Công viên", "Siêu thị"],
//       notes: "Giá còn thương lượng.",
//     },
//   },

//   {
//     id: 8,
//     name: "Căn hộ Sunrise City – Quận 7",
//     type: "Căn Hộ",
//     price: 6100000000,
//     area: 88,
//     address: "Nguyễn Hữu Thọ, Quận 7, TP.HCM",
//     bedrooms: 2,
//     bathrooms: 2,
//     direction: "Đông Nam",
//     images: ["/house2.jpg", "/house1.jpg"],
//     details: {
//       overview: "Căn hộ cao cấp Sunrise City, vị trí đẹp, tiện ích đầy đủ.",
//       highlights: ["Gần trung tâm Q7", "Tiện ích nội khu", "View thoáng"],
//       layout: ["2PN + 2WC"],
//       amenities: ["Hồ bơi", "Gym", "TTTM"],
//       notes: "Cho xem nhà linh hoạt.",
//     },
//   },

//   {
//     id: 9,
//     name: "Nhà phố Phú Nhuận – Hẻm xe hơi",
//     type: "Nhà Phố",
//     price: 9600000000,
//     area: 95,
//     address: "Phan Đăng Lưu, Phú Nhuận, TP.HCM",
//     bedrooms: 3,
//     bathrooms: 3,
//     direction: "Nam",
//     images: ["/house1.jpg", "/house2.jpg"],
//     details: {
//       overview:
//         "Nhà phố trung tâm Phú Nhuận, hẻm xe hơi, di chuyển sân bay chỉ 5 phút.",
//       highlights: [
//         "Vị trí trung tâm",
//         "Nhà mới, vào ở ngay",
//         "Khu dân trí cao",
//       ],
//       layout: ["1 trệt 2 lầu", "3PN + 3WC"],
//       amenities: ["Sân bay", "Chợ", "Trường học"],
//       notes: "Sổ hồng riêng.",
//     },
//   },

//   {
//     id: 10,
//     name: "Căn hộ Vinhomes Central Park – View sông",
//     type: "Căn Hộ",
//     price: 7800000000,
//     area: 90,
//     address: "Bình Thạnh, TP.HCM",
//     bedrooms: 3,
//     bathrooms: 2,
//     direction: "Đông Bắc",
//     images: ["/house2.jpg", "/house3.jpg"],
//     details: {
//       overview: "Căn hộ cao cấp ven sông Sài Gòn, không gian sống xanh.",
//       highlights: [
//         "View sông thoáng mát",
//         "Nội khu đẳng cấp",
//         "Cộng đồng cư dân văn minh",
//       ],
//       layout: ["3PN + 2WC"],
//       amenities: ["Công viên ven sông", "Mall", "Gym"],
//       notes: "Giá tốt trong khu.",
//     },
//   },

//   {
//     id: 11,
//     name: "Nhà phố Gò Vấp – Gần Emart",
//     type: "Nhà Phố",
//     price: 6900000000,
//     area: 85,
//     address: "Phan Văn Trị, Gò Vấp, TP.HCM",
//     bedrooms: 3,
//     bathrooms: 3,
//     direction: "Tây",
//     images: ["/house3.jpg", "/house1.jpg"],
//     details: {
//       overview: "Nhà phố khu Gò Vấp, tiện ích đầy đủ, phù hợp gia đình trẻ.",
//       highlights: ["Gần Emart", "Hẻm rộng", "Nhà mới"],
//       layout: ["1 trệt 2 lầu"],
//       amenities: ["Siêu thị", "Trường học"],
//       notes: "Có thể dọn vào ngay.",
//     },
//   },

//   {
//     id: 12,
//     name: "Biệt thự mini Quận 12",
//     type: "Biệt Thự",
//     price: 11500000000,
//     area: 180,
//     address: "Hà Huy Giáp, Quận 12, TP.HCM",
//     bedrooms: 4,
//     bathrooms: 4,
//     direction: "Bắc",
//     images: ["/house1.jpg", "/house3.jpg"],
//     details: {
//       overview:
//         "Biệt thự mini, không gian rộng rãi, thích hợp gia đình đông người.",
//       highlights: ["Sân đậu xe", "Khu yên tĩnh", "Giá tốt"],
//       layout: ["1 trệt 2 lầu"],
//       amenities: ["Công viên", "Siêu thị"],
//       notes: "Giá còn thương lượng.",
//     },
//   },

//   {
//     id: 13,
//     name: "Căn hộ Sunrise City – Quận 7",
//     type: "Căn Hộ",
//     price: 6100000000,
//     area: 88,
//     address: "Nguyễn Hữu Thọ, Quận 7, TP.HCM",
//     bedrooms: 2,
//     bathrooms: 2,
//     direction: "Đông Nam",
//     images: ["/house2.jpg", "/house1.jpg"],
//     details: {
//       overview: "Căn hộ cao cấp Sunrise City, vị trí đẹp, tiện ích đầy đủ.",
//       highlights: ["Gần trung tâm Quận 7", "Tiện ích nội khu", "View thoáng"],
//       layout: ["2PN + 2WC"],
//       amenities: ["Hồ bơi", "Gym", "TTTM"],
//       notes: "Cho xem nhà linh hoạt.",
//     },
//   },

//   {
//     id: 14,
//     name: "Căn hộ Masteri An Phú",
//     type: "Căn Hộ",
//     price: 5600000000,
//     area: 70,
//     address: "An Phú, TP Thủ Đức",
//     bedrooms: 2,
//     bathrooms: 2,
//     direction: "Đông",
//     images: ["/house3.jpg", "/house2.jpg"],
//     details: {
//       overview:
//         "Căn hộ cao cấp Masteri An Phú, phù hợp ở hoặc đầu tư cho thuê.",
//       highlights: ["Gần Metro", "Full tiện ích", "Thanh khoản cao"],
//       layout: ["2PN + 2WC"],
//       amenities: ["Hồ bơi", "Gym", "Mall"],
//       notes: "Giá tốt.",
//     },
//   },

//   {
//     id: 15,
//     name: "Nhà phố Quận 1 – Trung tâm",
//     type: "Nhà Phố",
//     price: 18500000000,
//     area: 110,
//     address: "Trần Hưng Đạo, Quận 1, TP.HCM",
//     bedrooms: 4,
//     bathrooms: 4,
//     direction: "Nam",
//     images: ["/house1.jpg", "/house2.jpg"],
//     details: {
//       overview: "Nhà phố trung tâm Quận 1, phù hợp vừa ở vừa kinh doanh.",
//       highlights: ["Vị trí cực hiếm", "Giá trị tăng cao", "Thanh khoản tốt"],
//       layout: ["1 trệt 3 lầu"],
//       amenities: ["Trung tâm thương mại", "Ngân hàng"],
//       notes: "Pháp lý đầy đủ.",
//     },
//   },

//   {
//     id: 16,
//     name: "Biệt thự ven sông Quận 9",
//     type: "Biệt Thự",
//     price: 32000000000,
//     area: 350,
//     address: "Long Trường, TP Thủ Đức",
//     bedrooms: 6,
//     bathrooms: 6,
//     direction: "Đông Bắc",
//     images: ["/house3.jpg", "/house1.jpg"],
//     details: {
//       overview: "Biệt thự ven sông, không gian sống đẳng cấp, yên tĩnh.",
//       highlights: ["View sông", "Sân vườn rộng", "Riêng tư"],
//       layout: ["1 trệt 2 lầu"],
//       amenities: ["Bến du thuyền", "Công viên"],
//       notes: "Khách VIP.",
//     },
//   },

//   {
//     id: 17,
//     name: "Căn hộ giá tốt Quận Bình Tân",
//     type: "Căn Hộ",
//     price: 3200000000,
//     area: 65,
//     address: "Bình Trị Đông, Bình Tân, TP.HCM",
//     bedrooms: 2,
//     bathrooms: 1,
//     direction: "Tây Nam",
//     images: ["/house2.jpg"],
//     details: {
//       overview: "Căn hộ giá tốt, phù hợp người mua ở thực.",
//       highlights: ["Giá rẻ", "Dễ cho thuê"],
//       layout: ["2PN + 1WC"],
//       amenities: ["Chợ", "Trường học"],
//       notes: "Thanh toán linh hoạt.",
//     },
//   },

//   {
//     id: 18,
//     name: "Nhà phố Tân Bình – Gần sân bay",
//     type: "Nhà Phố",
//     price: 8700000000,
//     area: 92,
//     address: "Cộng Hòa, Tân Bình, TP.HCM",
//     bedrooms: 3,
//     bathrooms: 3,
//     direction: "Bắc",
//     images: ["/house1.jpg", "/house3.jpg"],
//     details: {
//       overview: "Nhà phố gần sân bay, phù hợp ở hoặc cho thuê.",
//       highlights: ["Gần sân bay", "Giao thông thuận tiện"],
//       layout: ["1 trệt 2 lầu"],
//       amenities: ["Sân bay", "Trường học"],
//       notes: "Giá còn thương lượng.",
//     },
//   },

//   {
//     id: 19,
//     name: "Căn hộ cao cấp Empire City",
//     type: "Căn Hộ",
//     price: 14500000000,
//     area: 100,
//     address: "Thủ Thiêm, TP Thủ Đức",
//     bedrooms: 3,
//     bathrooms: 2,
//     direction: "Đông",
//     images: ["/house3.jpg", "/house2.jpg"],
//     details: {
//       overview: "Căn hộ cao cấp Empire City, view trung tâm Q1.",
//       highlights: ["View Landmark 81", "Tiện ích 5 sao"],
//       layout: ["3PN + 2WC"],
//       amenities: ["Hồ bơi vô cực", "Gym", "Sky lounge"],
//       notes: "Khách cao cấp.",
//     },
//   },

//   {
//     id: 20,
//     name: "Nhà phố Bình Thạnh – Gần Landmark",
//     type: "Nhà Phố",
//     price: 12500000000,
//     area: 105,
//     address: "Nguyễn Hữu Cảnh, Bình Thạnh, TP.HCM",
//     bedrooms: 4,
//     bathrooms: 4,
//     direction: "Đông Nam",
//     images: ["/house2.jpg", "/house1.jpg"],
//     details: {
//       overview: "Nhà phố gần Landmark 81, vị trí đẹp, tiềm năng tăng giá.",
//       highlights: ["Gần Landmark 81", "Dễ cho thuê"],
//       layout: ["1 trệt 3 lầu"],
//       amenities: ["Công viên", "TTTM"],
//       notes: "Sổ hồng riêng.",
//     },
//   },
// ];
