export const sampleProducts = [
  {
    id: 1,
    name: "Nhà phố Quận 7 – Khu Him Lam",
    type: "Nhà Phố",
    price: 8200000000,
    area: 120,
    address: "Nguyễn Thị Thập, Quận 7, TP.HCM",
    bedrooms: 4,
    bathrooms: 3,
    direction: "Đông Nam",
    images: ["/house1.jpg", "/house2.jpg", "/house3.jpg"],
    details: {
      overview:
        "Nhà phố 1 trệt 2 lầu, khu dân cư cao cấp, an ninh 24/7, thích hợp ở lâu dài.",
      highlights: [
        "Gần Lotte Mart, Crescent Mall",
        "Đường rộng, xe hơi đậu trước nhà",
        "Sổ hồng riêng, pháp lý rõ ràng",
      ],
      layout: [
        "Tầng trệt: PK + bếp + WC",
        "Lầu 1: 2PN + WC",
        "Lầu 2: 2PN + WC + sân phơi",
      ],
      amenities: ["Công viên", "Trường học", "Siêu thị"],
      notes: "Giá còn thương lượng nhẹ.",
    },
  },

  {
    id: 2,
    name: "Biệt thự Thảo Điền – Sân vườn rộng",
    type: "Biệt Thự",
    price: 24500000000,
    area: 300,
    address: "Xuân Thủy, Thảo Điền, TP Thủ Đức",
    bedrooms: 5,
    bathrooms: 6,
    direction: "Tây Bắc",
    images: ["/house2.jpg", "/house3.jpg", "/house1.jpg"],
    details: {
      overview:
        "Biệt thự cao cấp, khu người nước ngoài sinh sống, không gian yên tĩnh.",
      highlights: [
        "Sân vườn lớn ~80m²",
        "Thiết kế mở, nhiều ánh sáng",
        "Thích hợp ở hoặc cho thuê expat",
      ],
      layout: [
        "Tầng trệt: sân vườn + PK + bếp",
        "Lầu 1: 3PN",
        "Lầu 2: 2PN + sân thượng",
      ],
      amenities: ["Vincom Thảo Điền", "Metro", "Trường quốc tế"],
      notes: "Hỗ trợ ngân hàng.",
    },
  },

  {
    id: 3,
    name: "Căn hộ Masteri Centre Point",
    type: "Căn Hộ",
    price: 5200000000,
    area: 75,
    address: "Vinhomes Grand Park, TP Thủ Đức",
    bedrooms: 2,
    bathrooms: 2,
    direction: "Đông",
    images: ["/house3.jpg", "/house1.jpg"],
    details: {
      overview:
        "Căn hộ cao cấp, full nội thất, view công viên, tiện ích chuẩn resort.",
      highlights: ["Full nội thất", "View công viên 36ha", "An ninh 3 lớp"],
      layout: ["2PN + 2WC", "Ban công rộng"],
      amenities: ["Hồ bơi", "Gym", "Công viên"],
      notes: "Nhận nhà ngay.",
    },
  },

  {
    id: 4,
    name: "Nhà phố Phú Nhuận – Hẻm xe hơi",
    type: "Nhà Phố",
    price: 9600000000,
    area: 95,
    address: "Phan Đăng Lưu, Phú Nhuận, TP.HCM",
    bedrooms: 3,
    bathrooms: 3,
    direction: "Nam",
    images: ["/house1.jpg", "/house2.jpg"],
    details: {
      overview:
        "Nhà trung tâm Phú Nhuận, hẻm xe hơi, di chuyển sân bay 5 phút.",
      highlights: [
        "Vị trí trung tâm",
        "Nhà mới, vào ở ngay",
        "Khu dân trí cao",
      ],
      layout: ["1 trệt 2 lầu", "3PN + 3WC"],
      amenities: ["Sân bay", "Chợ", "Trường học"],
      notes: "Sổ riêng, công chứng nhanh.",
    },
  },

  {
    id: 5,
    name: "Căn hộ Vinhomes Central Park",
    type: "Căn Hộ",
    price: 7800000000,
    area: 90,
    address: "Bình Thạnh, TP.HCM",
    bedrooms: 3,
    bathrooms: 2,
    direction: "Đông Bắc",
    images: ["/house2.jpg", "/house3.jpg"],
    details: {
      overview: "Căn hộ cao cấp ven sông Sài Gòn, không gian sống xanh.",
      highlights: ["View sông", "Nội khu đẳng cấp", "Cộng đồng văn minh"],
      layout: ["3PN + 2WC"],
      amenities: ["Công viên ven sông", "Mall", "Gym"],
      notes: "Giá tốt trong khu.",
    },
  },

  {
    id: 6,
    name: "Nhà phố Gò Vấp – Gần Emart",
    type: "Nhà Phố",
    price: 6900000000,
    area: 85,
    address: "Phan Văn Trị, Gò Vấp, TP.HCM",
    bedrooms: 3,
    bathrooms: 3,
    direction: "Tây",
    images: ["/house3.jpg", "/house1.jpg"],
    details: {
      overview: "Nhà phố khu Gò Vấp, tiện ích đầy đủ, phù hợp gia đình trẻ.",
      highlights: ["Gần Emart", "Hẻm rộng", "Nhà mới"],
      layout: ["1 trệt 2 lầu"],
      amenities: ["Siêu thị", "Trường học"],
      notes: "Có thể dọn vào ngay.",
    },
  },

  {
    id: 7,
    name: "Biệt thự mini Quận 12",
    type: "Biệt Thự",
    price: 11500000000,
    area: 180,
    address: "Hà Huy Giáp, Quận 12, TP.HCM",
    bedrooms: 4,
    bathrooms: 4,
    direction: "Bắc",
    images: ["/house1.jpg", "/house3.jpg"],
    details: {
      overview:
        "Biệt thự mini, không gian rộng rãi, thích hợp gia đình đông người.",
      highlights: ["Sân đậu xe", "Khu yên tĩnh", "Giá tốt"],
      layout: ["1 trệt 2 lầu"],
      amenities: ["Công viên", "Siêu thị"],
      notes: "Giá còn thương lượng.",
    },
  },

  {
    id: 8,
    name: "Căn hộ Sunrise City – Quận 7",
    type: "Căn Hộ",
    price: 6100000000,
    area: 88,
    address: "Nguyễn Hữu Thọ, Quận 7, TP.HCM",
    bedrooms: 2,
    bathrooms: 2,
    direction: "Đông Nam",
    images: ["/house2.jpg", "/house1.jpg"],
    details: {
      overview: "Căn hộ cao cấp Sunrise City, vị trí đẹp, tiện ích đầy đủ.",
      highlights: ["Gần trung tâm Q7", "Tiện ích nội khu", "View thoáng"],
      layout: ["2PN + 2WC"],
      amenities: ["Hồ bơi", "Gym", "TTTM"],
      notes: "Cho xem nhà linh hoạt.",
    },
  },

  {
    id: 9,
    name: "Nhà phố Phú Nhuận – Hẻm xe hơi",
    type: "Nhà Phố",
    price: 9600000000,
    area: 95,
    address: "Phan Đăng Lưu, Phú Nhuận, TP.HCM",
    bedrooms: 3,
    bathrooms: 3,
    direction: "Nam",
    images: ["/house1.jpg", "/house2.jpg"],
    details: {
      overview:
        "Nhà phố trung tâm Phú Nhuận, hẻm xe hơi, di chuyển sân bay chỉ 5 phút.",
      highlights: [
        "Vị trí trung tâm",
        "Nhà mới, vào ở ngay",
        "Khu dân trí cao",
      ],
      layout: ["1 trệt 2 lầu", "3PN + 3WC"],
      amenities: ["Sân bay", "Chợ", "Trường học"],
      notes: "Sổ hồng riêng.",
    },
  },

  {
    id: 10,
    name: "Căn hộ Vinhomes Central Park – View sông",
    type: "Căn Hộ",
    price: 7800000000,
    area: 90,
    address: "Bình Thạnh, TP.HCM",
    bedrooms: 3,
    bathrooms: 2,
    direction: "Đông Bắc",
    images: ["/house2.jpg", "/house3.jpg"],
    details: {
      overview: "Căn hộ cao cấp ven sông Sài Gòn, không gian sống xanh.",
      highlights: [
        "View sông thoáng mát",
        "Nội khu đẳng cấp",
        "Cộng đồng cư dân văn minh",
      ],
      layout: ["3PN + 2WC"],
      amenities: ["Công viên ven sông", "Mall", "Gym"],
      notes: "Giá tốt trong khu.",
    },
  },

  {
    id: 11,
    name: "Nhà phố Gò Vấp – Gần Emart",
    type: "Nhà Phố",
    price: 6900000000,
    area: 85,
    address: "Phan Văn Trị, Gò Vấp, TP.HCM",
    bedrooms: 3,
    bathrooms: 3,
    direction: "Tây",
    images: ["/house3.jpg", "/house1.jpg"],
    details: {
      overview: "Nhà phố khu Gò Vấp, tiện ích đầy đủ, phù hợp gia đình trẻ.",
      highlights: ["Gần Emart", "Hẻm rộng", "Nhà mới"],
      layout: ["1 trệt 2 lầu"],
      amenities: ["Siêu thị", "Trường học"],
      notes: "Có thể dọn vào ngay.",
    },
  },

  {
    id: 12,
    name: "Biệt thự mini Quận 12",
    type: "Biệt Thự",
    price: 11500000000,
    area: 180,
    address: "Hà Huy Giáp, Quận 12, TP.HCM",
    bedrooms: 4,
    bathrooms: 4,
    direction: "Bắc",
    images: ["/house1.jpg", "/house3.jpg"],
    details: {
      overview:
        "Biệt thự mini, không gian rộng rãi, thích hợp gia đình đông người.",
      highlights: ["Sân đậu xe", "Khu yên tĩnh", "Giá tốt"],
      layout: ["1 trệt 2 lầu"],
      amenities: ["Công viên", "Siêu thị"],
      notes: "Giá còn thương lượng.",
    },
  },

  {
    id: 13,
    name: "Căn hộ Sunrise City – Quận 7",
    type: "Căn Hộ",
    price: 6100000000,
    area: 88,
    address: "Nguyễn Hữu Thọ, Quận 7, TP.HCM",
    bedrooms: 2,
    bathrooms: 2,
    direction: "Đông Nam",
    images: ["/house2.jpg", "/house1.jpg"],
    details: {
      overview: "Căn hộ cao cấp Sunrise City, vị trí đẹp, tiện ích đầy đủ.",
      highlights: ["Gần trung tâm Quận 7", "Tiện ích nội khu", "View thoáng"],
      layout: ["2PN + 2WC"],
      amenities: ["Hồ bơi", "Gym", "TTTM"],
      notes: "Cho xem nhà linh hoạt.",
    },
  },

  {
    id: 14,
    name: "Căn hộ Masteri An Phú",
    type: "Căn Hộ",
    price: 5600000000,
    area: 70,
    address: "An Phú, TP Thủ Đức",
    bedrooms: 2,
    bathrooms: 2,
    direction: "Đông",
    images: ["/house3.jpg", "/house2.jpg"],
    details: {
      overview:
        "Căn hộ cao cấp Masteri An Phú, phù hợp ở hoặc đầu tư cho thuê.",
      highlights: ["Gần Metro", "Full tiện ích", "Thanh khoản cao"],
      layout: ["2PN + 2WC"],
      amenities: ["Hồ bơi", "Gym", "Mall"],
      notes: "Giá tốt.",
    },
  },

  {
    id: 15,
    name: "Nhà phố Quận 1 – Trung tâm",
    type: "Nhà Phố",
    price: 18500000000,
    area: 110,
    address: "Trần Hưng Đạo, Quận 1, TP.HCM",
    bedrooms: 4,
    bathrooms: 4,
    direction: "Nam",
    images: ["/house1.jpg", "/house2.jpg"],
    details: {
      overview: "Nhà phố trung tâm Quận 1, phù hợp vừa ở vừa kinh doanh.",
      highlights: ["Vị trí cực hiếm", "Giá trị tăng cao", "Thanh khoản tốt"],
      layout: ["1 trệt 3 lầu"],
      amenities: ["Trung tâm thương mại", "Ngân hàng"],
      notes: "Pháp lý đầy đủ.",
    },
  },

  {
    id: 16,
    name: "Biệt thự ven sông Quận 9",
    type: "Biệt Thự",
    price: 32000000000,
    area: 350,
    address: "Long Trường, TP Thủ Đức",
    bedrooms: 6,
    bathrooms: 6,
    direction: "Đông Bắc",
    images: ["/house3.jpg", "/house1.jpg"],
    details: {
      overview: "Biệt thự ven sông, không gian sống đẳng cấp, yên tĩnh.",
      highlights: ["View sông", "Sân vườn rộng", "Riêng tư"],
      layout: ["1 trệt 2 lầu"],
      amenities: ["Bến du thuyền", "Công viên"],
      notes: "Khách VIP.",
    },
  },

  {
    id: 17,
    name: "Căn hộ giá tốt Quận Bình Tân",
    type: "Căn Hộ",
    price: 3200000000,
    area: 65,
    address: "Bình Trị Đông, Bình Tân, TP.HCM",
    bedrooms: 2,
    bathrooms: 1,
    direction: "Tây Nam",
    images: ["/house2.jpg"],
    details: {
      overview: "Căn hộ giá tốt, phù hợp người mua ở thực.",
      highlights: ["Giá rẻ", "Dễ cho thuê"],
      layout: ["2PN + 1WC"],
      amenities: ["Chợ", "Trường học"],
      notes: "Thanh toán linh hoạt.",
    },
  },

  {
    id: 18,
    name: "Nhà phố Tân Bình – Gần sân bay",
    type: "Nhà Phố",
    price: 8700000000,
    area: 92,
    address: "Cộng Hòa, Tân Bình, TP.HCM",
    bedrooms: 3,
    bathrooms: 3,
    direction: "Bắc",
    images: ["/house1.jpg", "/house3.jpg"],
    details: {
      overview: "Nhà phố gần sân bay, phù hợp ở hoặc cho thuê.",
      highlights: ["Gần sân bay", "Giao thông thuận tiện"],
      layout: ["1 trệt 2 lầu"],
      amenities: ["Sân bay", "Trường học"],
      notes: "Giá còn thương lượng.",
    },
  },

  {
    id: 19,
    name: "Căn hộ cao cấp Empire City",
    type: "Căn Hộ",
    price: 14500000000,
    area: 100,
    address: "Thủ Thiêm, TP Thủ Đức",
    bedrooms: 3,
    bathrooms: 2,
    direction: "Đông",
    images: ["/house3.jpg", "/house2.jpg"],
    details: {
      overview: "Căn hộ cao cấp Empire City, view trung tâm Q1.",
      highlights: ["View Landmark 81", "Tiện ích 5 sao"],
      layout: ["3PN + 2WC"],
      amenities: ["Hồ bơi vô cực", "Gym", "Sky lounge"],
      notes: "Khách cao cấp.",
    },
  },

  {
    id: 20,
    name: "Nhà phố Bình Thạnh – Gần Landmark",
    type: "Nhà Phố",
    price: 12500000000,
    area: 105,
    address: "Nguyễn Hữu Cảnh, Bình Thạnh, TP.HCM",
    bedrooms: 4,
    bathrooms: 4,
    direction: "Đông Nam",
    images: ["/house2.jpg", "/house1.jpg"],
    details: {
      overview: "Nhà phố gần Landmark 81, vị trí đẹp, tiềm năng tăng giá.",
      highlights: ["Gần Landmark 81", "Dễ cho thuê"],
      layout: ["1 trệt 3 lầu"],
      amenities: ["Công viên", "TTTM"],
      notes: "Sổ hồng riêng.",
    },
  },
];
