export const sampleRentals = [
  {
    id: 1,
    name: "Căn hộ Masteri Thảo Điền – Full nội thất",
    type: "Căn Hộ",
    rentalPeriod: "Dài hạn",
    price: 22000000, // / tháng
    area: 70,
    address: "Thảo Điền, TP Thủ Đức, TP.HCM",
    bedrooms: 2,
    bathrooms: 2,
    direction: "Đông Nam",
    images: ["/rent/r1.jpg", "/rent/r2.jpg"],
    details: {
      overview: "Căn hộ cao cấp Masteri Thảo Điền, full nội thất, vào ở ngay.",
      highlights: ["Full nội thất", "Gần Metro số 1", "An ninh 24/7"],
      amenities: ["Hồ bơi", "Gym", "TTTM", "Công viên"],
      notes: "Hợp đồng tối thiểu 1 năm.",
    },
  },

  {
    id: 2,
    name: "Nhà phố Quận 7 – Khu Him Lam",
    type: "Nhà Phố",
    rentalPeriod: "Dài hạn",
    price: 45000000,
    area: 120,
    address: "Nguyễn Thị Thập, Quận 7, TP.HCM",
    bedrooms: 4,
    bathrooms: 3,
    direction: "Nam",
    images: ["/rent/r3.jpg", "/rent/r4.jpg"],
    details: {
      overview:
        "Nhà phố khu Him Lam, đường rộng, phù hợp ở gia đình hoặc làm văn phòng.",
      highlights: [
        "Khu dân cư cao cấp",
        "Xe hơi đậu trước nhà",
        "Gần Lotte Mart",
      ],
      amenities: ["Trường học", "Siêu thị", "Công viên"],
      notes: "Cọc 2 tháng, thanh toán linh hoạt.",
    },
  },

  {
    id: 3,
    name: "Biệt thự Thảo Điền – Có sân vườn",
    type: "Biệt Thự",
    rentalPeriod: "Dài hạn",
    price: 95000000,
    area: 300,
    address: "Xuân Thủy, Thảo Điền, TP Thủ Đức",
    bedrooms: 5,
    bathrooms: 5,
    direction: "Đông",
    images: ["/rent/r5.jpg"],
    details: {
      overview:
        "Biệt thự Thảo Điền, sân vườn rộng, phù hợp gia đình hoặc expat.",
      highlights: [
        "Sân vườn riêng",
        "Không gian yên tĩnh",
        "Khu người nước ngoài",
      ],
      amenities: ["Trường quốc tế", "Siêu thị", "Café"],
      notes: "Ưu tiên khách thuê lâu dài.",
    },
  },

  {
    id: 4,
    name: "Văn phòng Quận 1 – Mặt tiền Nguyễn Huệ",
    type: "Văn Phòng",
    rentalPeriod: "Dài hạn",
    price: 120000000,
    area: 150,
    address: "Nguyễn Huệ, Quận 1, TP.HCM",
    bedrooms: 0,
    bathrooms: 2,
    direction: "Đông Bắc",
    images: ["/rent/r6.jpg"],
    details: {
      overview:
        "Văn phòng cao cấp ngay phố đi bộ Nguyễn Huệ, vị trí trung tâm.",
      highlights: ["Mặt tiền Quận 1", "Thang máy", "Bảo vệ 24/7"],
      amenities: ["Bãi xe", "Thang máy", "Lễ tân"],
      notes: "Giá chưa bao gồm VAT.",
    },
  },

  {
    id: 5,
    name: "ShopHouse Vinhomes Grand Park",
    type: "ShopHouse",
    rentalPeriod: "Dài hạn",
    price: 60000000,
    area: 90,
    address: "Vinhomes Grand Park, TP Thủ Đức",
    bedrooms: 0,
    bathrooms: 2,
    direction: "Tây",
    images: ["/rent/r7.jpg"],
    details: {
      overview: "ShopHouse khối đế Vinhomes Grand Park, phù hợp kinh doanh.",
      highlights: ["Lưu lượng cư dân đông", "Mặt tiền đẹp", "Dễ kinh doanh"],
      amenities: ["Bãi xe", "Công viên", "TTTM"],
      notes: "Không giới hạn ngành nghề sạch.",
    },
  },

  {
    id: 6,
    name: "Nhà xưởng Bình Tân – Diện tích lớn",
    type: "Nhà Xưởng",
    rentalPeriod: "Dài hạn",
    price: 180000000,
    area: 1000,
    address: "Bình Trị Đông, Bình Tân, TP.HCM",
    bedrooms: 0,
    bathrooms: 4,
    direction: "Tây Nam",
    images: ["/rent/r8.jpg"],
    details: {
      overview: "Nhà xưởng lớn tại Bình Tân, xe container ra vào dễ dàng.",
      highlights: ["Diện tích lớn", "Điện 3 pha", "Container vào tận nơi"],
      amenities: ["Bãi xe", "Kho bãi"],
      notes: "Hợp đồng tối thiểu 2 năm.",
    },
  },

  {
    id: 7,
    name: "Căn hộ Studio Quận 4 – Ngắn hạn",
    type: "Căn Hộ",
    rentalPeriod: "Ngắn hạn",
    price: 15000000,
    area: 40,
    address: "Quận 4, TP.HCM",
    bedrooms: 1,
    bathrooms: 1,
    direction: "Đông",
    images: ["/rent/r9.jpg"],
    details: {
      overview: "Căn hộ studio cho thuê ngắn hạn, đầy đủ nội thất.",
      highlights: ["Ở ngắn hạn", "Full nội thất", "Gần Quận 1"],
      amenities: ["Wifi", "Máy giặt", "Bảo vệ"],
      notes: "Thuê tối thiểu 3 tháng.",
    },
  },
];
