const AUDIT_ACTIONS = {
  LOGIN: "LOGIN",
  REFRESH: "REFRESH",
  CREATE: "CREATE",
  UPDATE: "UPDATE",
  DELETE: "DELETE",
  SUBMIT: "SUBMIT",
  APPROVE: "APPROVE",
  REJECT: "REJECT",
  ARCHIVE: "ARCHIVE",
};

const AUDIT_RESOURCES = {
  AUTH: "AUTH",
  USER: "USER",
  PROPERTY: "PROPERTY",
  POST: "POST",
};

module.exports = { AUDIT_ACTIONS, AUDIT_RESOURCES };
